# Generated by Django 5.0.6 on 2024-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshopapp', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sport', 'sport'), ('action', 'action'), ('fighting', 'fighting'), ('battle royale', 'battle royale'), ('action', 'action'), ('role playing', 'role playing')], max_length=200),
        ),
    ]
