# Generated by Django 5.0.6 on 2024-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshopapp', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1, verbose_name=range(1, 5)),
            preserve_default=False,
        ),
    ]
